# Generated by Django 5.2.9 on 2025-12-10 03:39

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Dispositivo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('tipo', models.CharField(choices=[('SIRENA', 'Sirena'), ('PORTON', 'Portón Automático'), ('LUZ', 'Luz de Emergencia'), ('RADIO', 'Radio'), ('SENSOR', 'Sensor')], max_length=20)),
                ('direccion_red', models.GenericIPAddressField(blank=True, null=True)),
                ('ubicacion', models.CharField(blank=True, max_length=200)),
                ('estado', models.CharField(default='ACTIVO', max_length=20)),
                ('ultima_comunicacion', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='LogSistema',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nivel', models.CharField(max_length=20)),
                ('componente', models.CharField(max_length=80)),
                ('mensaje', models.TextField()),
                ('meta', models.JSONField(blank=True, null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Incidente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('FUEGO_ESTRUCTURAL', '🔥 Fuego Estructural'), ('RESCATE', '🦺 Rescate'), ('ACCIDENTE', '🚑 Accidente'), ('FUEGO_FORESTAL', '🌲 Fuego Forestal'), ('MATERIALES_PELIGROSOS', '⚠️ Materiales Peligrosos'), ('OTRO', '📋 Otro')], max_length=50)),
                ('direccion', models.CharField(max_length=200)),
                ('detalles', models.TextField()),
                ('prioridad_alta', models.BooleanField(default=False)),
                ('estado', models.CharField(choices=[('REPORTADO', 'Reportado'), ('ASIGNADO', 'Asignado'), ('EN_CURSO', 'En Curso'), ('CERRADO', 'Cerrado')], default='REPORTADO', max_length=20)),
                ('fecha_registro', models.DateTimeField(default=django.utils.timezone.now)),
                ('fecha_cierre', models.DateTimeField(blank=True, null=True)),
                ('coordenadas_lat', models.FloatField(blank=True, null=True)),
                ('coordenadas_lng', models.FloatField(blank=True, null=True)),
                ('operador', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='incidentes_atendidos', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-fecha_registro'],
            },
        ),
        migrations.CreateModel(
            name='AccionIoT',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(max_length=40)),
                ('accion', models.CharField(max_length=50)),
                ('detalles', models.JSONField(blank=True, default=dict, null=True)),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now)),
                ('resultado', models.CharField(blank=True, max_length=100, null=True)),
                ('dispositivo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='incidentes.dispositivo')),
                ('incidente', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='incidentes.incidente')),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='Llamada',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.CharField(max_length=20)),
                ('titular', models.CharField(max_length=100)),
                ('fecha_hora', models.DateTimeField(default=django.utils.timezone.now)),
                ('duracion', models.DurationField(blank=True, null=True)),
                ('incidente_relacionado', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='incidentes.incidente')),
            ],
            options={
                'ordering': ['-fecha_hora'],
            },
        ),
        migrations.CreateModel(
            name='Movil',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.CharField(max_length=10, unique=True)),
                ('tipo', models.CharField(choices=[('AUTOBOMBA', 'Autobomba'), ('ESCALERA', 'Escalera'), ('RESCATE', 'Unidad de Rescate'), ('MEDICA', 'Unidad Médica'), ('HAZMAT', 'Hazmat'), ('COMANDO', 'Vehículo de Comando')], max_length=20)),
                ('estado', models.CharField(choices=[('EN_SERVICIO', 'En Servicio'), ('FUERA_SERVICIO', 'Fuera de Servicio'), ('EN_CAMINO', 'En Camino'), ('EN_INTERVENCION', 'En Intervención'), ('REG_RESERVA', 'En Reserva')], default='EN_SERVICIO', max_length=20)),
                ('ultima_actualizacion', models.DateTimeField(default=django.utils.timezone.now)),
                ('detalles', models.TextField(blank=True)),
                ('incidente_actual', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='moviles_asignados', to='incidentes.incidente')),
            ],
            options={
                'verbose_name_plural': 'Móviles',
                'ordering': ['numero'],
            },
        ),
        migrations.CreateModel(
            name='TiemposIncidente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hora_registro', models.DateTimeField(blank=True, null=True)),
                ('hora_despacho', models.DateTimeField(blank=True, null=True)),
                ('hora_en_ruta', models.DateTimeField(blank=True, null=True)),
                ('hora_llegada', models.DateTimeField(blank=True, null=True)),
                ('hora_cierre', models.DateTimeField(blank=True, null=True)),
                ('incidente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tiempos', to='incidentes.incidente')),
            ],
        ),
    ]
